name: deploy wallet embed sample prod

on:
  release:
    types: [published]

jobs:
  build-deploy:
    # 実行するインスタンス
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["14.x"]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm Install
        run: |
          npm install
      - name: Build
        env:
          NODE_ENV: "development"
          REACT_APP_EMBED_BUILD_ENV: "production"
          REACT_APP_GOOGLE_CLIENT_ID: "hxFv4SaQVXv3tE_rhe5u9"
          REACT_APP_LINE_CLIENT_ID: "wa3wjaB0dx0RO9AgzngM-"
          REACT_APP_LOGIN_UPBOND_DOMAIN: "https://auth.upbond.io"
          REACT_APP_CLIENT_ID: "BKmNTSQ7y8yWyhNT_W5BobaAu7Re-zLW6fzK0bzdvjP9a-G4OP8ajriQJHFOH3ypvRIJeEp_O40aag-7iNTyp-s"
          REACT_APP_SENTRY_DSN: 'https://a50ce9a8992645578b8411e379792588@o1367795.ingest.sentry.io/4504670985846784'
        run: DISABLE_ESLINT_PLUGIN=true npm run build

      - name: upload-s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "upbond-embed-sample-prod"
          AWS_ACCESS_KEY_ID: ${{ secrets.ORG_AWS_ADMIN_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ORG_AWS_ADMIN_SECRET_KEY }}
          AWS_REGION: 'ap-northeast-1'   # optional: defaults to us-east-1
          SOURCE_DIR: './build'      # optional: defaults to entire repository

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: "E2X8WEHMADV7TD"
          PATHS: "/index.html"
          AWS_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.ORG_AWS_ADMIN_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ORG_AWS_ADMIN_SECRET_KEY }}
          